project_id = "ookvohtvmjcgrfahigyr"

[functions.champro-api]
verify_jwt = true

[functions.champro-embed-key]
verify_jwt = false

[functions.champro-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.champro-seed-skus]
verify_jwt = false

[functions.champro-cart-item]
verify_jwt = false

[functions.generate-flyer]
verify_jwt = false

[functions.download-flyer]
verify_jwt = false
