project_id = "ookvohtvmjcgrfahigyr"

[functions.champro-api]
verify_jwt = true

[functions.champro-embed-key]
verify_jwt = false

[functions.champro-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
